// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace ca3.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using ca3;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "D:\College\Year 4\EAD\ca3\ca3\ca3\_Imports.razor"
using ca3.Shared;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/servicesTitles/{serviceId:int}")]
    public partial class ServicesTitles : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 81 "D:\College\Year 4\EAD\ca3\ca3\ca3\Pages\ServicesTitles.razor"
       


    [Parameter]
    public int serviceId { get; set; }

    private Titles titlesList;
    private int page = 1;
    private Genres[] genres;
    private int genre = int.MaxValue;
    private Countries[] regions;
    private string region = "us";

    public void setGenre(ChangeEventArgs e)
    {
        genre = Int32.Parse(e.Value.ToString());
    }

    public void setRegion(ChangeEventArgs e)
    {
        region = e.Value.ToString();
    }

    public int totalOnPage()
    {
        return (titlesList.titles.Count * page);
    }
    public int firstOnPage()
    {
        return ((page - 1) * 250 + 1);
    }

    public async Task nextPage()
    {
        if (page < titlesList.total_pages && titlesList.titles.Count != 0)
        {
            page += 1;
            if (genre != int.MaxValue)
            {
                string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}&regions={region}&page={page}&genres={genre}";
                titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
            }
            else
            {
                string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}&regions={region}&page={page}";
                titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
            }

        }
    }

    public async Task PreiousPage()
    {
        if (page != 1)
        {
            page -= 1;
            if (genre != int.MaxValue)
            {
                string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}&regions={region}&page={page}&genres={genre}";
                titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
            }
            else
            {
                string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}&regions={region}&page={page}";
                titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
            }

        }
    }

    public async Task getFiltered()
    {
        if (genre != int.MaxValue)
        {
            string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}&regions={region}&page={page}&genres={genre}";
            titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
        }
        else
        {
            string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}&regions={region}&page={page}";
            titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
        }

    }

    protected override async Task OnInitializedAsync()
    {
        string httpString = $"https://api.watchmode.com/v1/list-titles/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m&source_ids={serviceId}";
        titlesList = await Http.GetFromJsonAsync<Titles>(httpString);
        genres = await Http.GetFromJsonAsync<Genres[]>("https://api.watchmode.com/v1/genres/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m");
        regions = await Http.GetFromJsonAsync<Countries[]>("https://api.watchmode.com/v1/regions/?apiKey=yvWxtCM9fYbj3Zg5NmEEK6bJtJnPSe6C6XfFj11m");
    }

    public class Title
    {
        public int id { get; set; }
        public string title { get; set; }
        public int year { get; set; }
        public string imdb_id { get; set; }
        public int tmdb_id { get; set; }
        public string tmdb_type { get; set; }
        public string type { get; set; }
    }

    public class Titles
    {
        public List<Title> titles { get; set; }
        public int page { get; set; }
        public int total_results { get; set; }
        public int total_pages { get; set; }
    }

    public class Genres
    {
        public int id { get; set; }
        public string name { get; set; }
        public int? tmdb_id { get; set; }
    }

    public class Countries
    {
        public string country { get; set; }
        public string name { get; set; }
        public string flag { get; set; }
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
